alias ls="ls -CF --color=auto"
alias vless="/usr/share/vim/vim81/macros/less.sh"
alias ghtoken="xclip -sel clip < ${HOME}/.github-tokens.txt"
alias apti="apt list --installed 2> /dev/null"
alias open="xdg-open"
